export const SET_MENU_LIST = 'SET_MENU_LIST'

export const UPDATE_COLLAPSE = 'UPDATE_COLLAPSE'

export const SET_BREADCRUMBS = 'SET_BREADCRUMBS'

export const SET_TAGS_LIST = 'SET_TAGS_LIST'

export const SET_TAGS_ACTIVE = 'SET_TAGS_ACTIVE'